openapi: 3.0.0
info:
  title: app-orders
  version: '1.0'
servers:
  - url: 'http://localhost:3000/app'
paths:
  /orders:
    post:
      summary: ''
      operationId: post-orders
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
components:
  schemas:
    order:
      title: order
      allOf:
        - $ref: ../models/order.v1.yaml
        - type: object
          properties:
            partnerId:
              type: string
