openapi: 3.0.0
info:
  title: pos-orders
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/orders/{orderId}':
    parameters:
      - type: string
        name: orderId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: get-orders
      parameters:
        - schema:
            type: string
          in: query
          name: orderId
components:
  schemas:
    order:
      title: order
      allOf:
        - $ref: ../models/order.v1.yaml
        - type: object
          properties:
            appName:
              type: string
